name: CI Pipeline

on:
  push:
    branches:
      - master

  workflow_dispatch:

jobs:
  build:
    runs-on: webserver   # self-hosted runner label

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run a one-line script
        run: echo "Hello, world! from $(hostname) Host"

      - name: Run a multi-line script
        run: |
          echo "Add other actions to build,"
          echo "test, and deploy your project."

  deploy_job:
    runs-on: webserver

    steps:
      - name: Deploy step
        run: |
          echo "Listing workspace files"
          ls ${{ github.workspace }}
